backend:
  name: git-gateway
  branch: master
media_folder: "public/images" # Media files will be stored in the repo under public/images

media_library: # Using Cloudinary to manage images
  name: cloudinary
  output_filename_only: false
  config:
    cloud_name: dnf1xnzg3
    api_key: 897742946478848
    default_transformations:
      - fetch_format: auto
        width: auto
        quality: auto
        crop: fill

public_folder: "/images" # The src attribute for uploaded media will begin with /images
collections:
  - name: "news"
    label: "News"
    folder: "src/news"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "news"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list", default: ["news"]}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Image caption", name: "imageAlt", widget: "string"}
      - {label: "Introduction", name: "newsIntro", widget: "markdown"}
      - {label: "News - second introduction", name: "newsText", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "plants"
    label: "Plants"
    folder: "src/plants"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "plants"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list", default: ["plants"]}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Image caption", name: "imageAlt", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Introduction", name: "introduction", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown"}